import { NextResponse } from 'next/server';

import { getBusinessDateValue } from '@/lib/business-date';
import {
    computePurchaseSummary,
    computePurchaseStatus,
    isInventoryUnit,
    isTireTrackedWarehouseItem,
    parseInventoryQuantity,
    parseWholeMoneyAmount,
} from '@/lib/inventory';
import {
    createDocument,
    deleteDocument,
    getDocumentById,
    listDocumentsByFilter,
    updateDocument,
} from '@/lib/repositories/document-store';
import { buildTireHistoryLogDoc, buildTireHistorySnapshot } from '@/lib/tire-history';
import { buildAutoGeneratedTireCode, buildTrackedTireStockMovementDoc } from '@/lib/tire-inventory';
import { normalizeOptionalTireType, normalizeTireType } from '@/lib/tire-types';
import { hasPermission } from '@/lib/rbac';
import type {
    Purchase,
    PurchaseItem,
    PurchasePayment,
    SupplierItemPrice,
    StockMovement,
    StockMovementSourceType,
    TireEvent,
    Supplier,
    WarehouseItem,
} from '@/lib/types';

import {
    assertIsoDate,
    computeLedgerDebitBalance,
    getLedgerAccount,
    normalizeOptionalText,
    normalizeText,
    type ApiSession,
} from './data-helpers';
import { recomputeBankLedgerBalancesForAccounts } from './bank-balance-helpers';
import { normalizeWarehouseItemPayload } from './generic-workflow-support';
import { getLatestWarehouseStockMovementDateMap } from './inventory-stock-support';
import {
    postPurchasePaymentJournal,
    postPurchaseReceiptJournal,
    postStockMovementJournal,
} from './accounting-posting';

type AuditLogFn = (
    session: Pick<ApiSession, '_id' | 'name'>,
    action: string,
    entityType: string,
    entityRef: string,
    summary: string
) => void | Promise<void>;

type PurchaseNewItemInput = {
    name: string;
    code?: string;
    category?: string;
    unit: string;
    trackingMode: 'STANDARD' | 'TIRE_ASSET';
    tireTypeDefault?: string;
    tireBrandDefault?: string;
    tireSizeDefault?: string;
};

type PurchaseCreateLine = {
    warehouseItemRef?: string;
    newItem?: PurchaseNewItemInput;
    supplierItemPriceRef?: string;
    orderedQty: number;
    unitPrice: number;
    priceOverrideReason?: string;
    notes?: string;
};

type SupplierDocument = Supplier & { _rev?: string };
type PurchaseDocument = Purchase & { _rev?: string };
type PurchaseItemDocument = PurchaseItem & { _rev?: string };
type SupplierItemPriceDocument = SupplierItemPrice & { _rev?: string };
type WarehouseItemDocument = WarehouseItem & { _rev?: string };

function formatAuditMoney(amount: number) {
    return `Rp ${Math.round(amount).toLocaleString('id-ID')}`;
}

function buildPurchaseNumber(dateValue: string, sequence: number) {
    const normalized = dateValue.replace(/-/g, '').slice(0, 6);
    return `PO-${normalized}-${String(sequence).padStart(4, '0')}`;
}

async function getNextPurchaseNumber(orderDate: string) {
    const period = orderDate.slice(0, 7).replace('-', '');
    // PERF: Filter by orderDate range at query level instead of fetching all purchases
    const monthStart = `${period.slice(0, 4)}-${period.slice(4, 6)}-01`;
    const monthEnd = `${period.slice(0, 4)}-${period.slice(4, 6)}-31`;
    const existing = await listDocumentsByFilter<{ purchaseNumber?: string; orderDate?: string }>('purchase', {
        orderDate__gte: monthStart,
        orderDate__lte: monthEnd,
    });
    const maxSequence = existing.reduce((max, row) => {
        const match = typeof row.purchaseNumber === 'string'
            ? row.purchaseNumber.match(/(\d{4})$/)
            : null;
        const parsed = match ? Number.parseInt(match[1], 10) : 0;
        return parsed > max ? parsed : max;
    }, 0);
    return buildPurchaseNumber(`${period.slice(0, 4)}-${period.slice(4, 6)}-01`, maxSequence + 1);
}

function buildWarehouseItemCode(period: string, sequence: number) {
    return `BRG-${period}-${String(sequence).padStart(4, '0')}`;
}

async function getNextWarehouseItemCode(dateValue: string) {
    const period = dateValue.slice(0, 7).replace('-', '');
    const prefix = `BRG-${period}-`;
    const existing = await listDocumentsByFilter<{ itemCode?: string }>('warehouseItem', {
        itemCode__gte: prefix,
        itemCode__lte: `${prefix}\uffff`,
    });
    const maxSequence = existing.reduce((max, row) => {
        const match = typeof row.itemCode === 'string'
            ? row.itemCode.match(/(\d{4})$/)
            : null;
        const parsed = match ? Number.parseInt(match[1], 10) : 0;
        return parsed > max ? parsed : max;
    }, 0);
    return buildWarehouseItemCode(period, maxSequence + 1);
}

async function findActiveWarehouseItemByName(name: string) {
    const candidates = await listDocumentsByFilter<WarehouseItemDocument>('warehouseItem', { name });
    return candidates.find(item => item.active !== false && String(item.name).toLowerCase() === name.toLowerCase()) || null;
}

async function loadPurchaseBundle(purchaseId: string) {
    const [purchase, items, payments] = await Promise.all([
        getDocumentById<PurchaseDocument>(purchaseId, 'purchase'),
        listDocumentsByFilter<PurchaseItemDocument>('purchaseItem', { purchaseRef: purchaseId }),
        listDocumentsByFilter<PurchasePayment>('purchasePayment', { purchaseRef: purchaseId }),
    ]);
    if (!purchase || purchase._type !== 'purchase') {
        return null;
    }
    return {
        purchase,
        items: [...items].sort((left, right) =>
            String((left as unknown as { _createdAt?: string })._createdAt || '')
                .localeCompare(String((right as unknown as { _createdAt?: string })._createdAt || ''))
        ),
        payments: [...payments].sort((left, right) => {
            const byDate = String(left.date || '').localeCompare(String(right.date || ''));
            if (byDate !== 0) return byDate;
            return String((left as unknown as { _createdAt?: string })._createdAt || '')
                .localeCompare(String((right as unknown as { _createdAt?: string })._createdAt || ''));
        }),
    };
}

function buildPurchaseAuditSummary(purchaseNumber: string, supplierName: string, totalAmount: number) {
    return `Pembelian ${purchaseNumber} ke ${supplierName} sebesar ${formatAuditMoney(totalAmount)}`;
}

function buildPurchasePaymentAuditSummary(input: {
    purchaseNumber: string;
    supplierName: string;
    amount: number;
    bankName: string;
    note?: string;
}) {
    const base = `Bayar supplier ${formatAuditMoney(input.amount)} untuk ${input.purchaseNumber} (${input.supplierName}) via ${input.bankName}`;
    return input.note ? `${base} - ${input.note}` : base;
}

function normalizeDateOnly(value: string | undefined | null) {
    return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}/.test(value)
        ? value.slice(0, 10)
        : '';
}

function buildStockMovementAuditSummary(input: {
    itemName: string;
    itemCode: string;
    quantity: number;
    sourceType: StockMovementSourceType;
    note?: string;
}) {
    const action = input.sourceType === 'MANUAL_OUT' ? 'Stok keluar' : 'Stok masuk';
    const base = `${action} ${input.itemCode} - ${input.itemName} sebanyak ${input.quantity}`;
    return input.note ? `${base} - ${input.note}` : base;
}

async function resolveSupplierSnapshot(supplierRef: string) {
    const supplier = await getDocumentById<SupplierDocument>(supplierRef, 'supplier');
    if (!supplier || supplier._type !== 'supplier') {
        throw new Error('Supplier tidak ditemukan');
    }
    if (supplier.active === false) {
        throw new Error('Supplier tidak aktif');
    }
    return supplier;
}

async function resolveWarehouseItemSnapshot(itemRef: string, options?: { allowInactive?: boolean }) {
    const item = await getDocumentById<WarehouseItemDocument>(itemRef, 'warehouseItem');
    if (!item || item._type !== 'warehouseItem') {
        throw new Error('Barang gudang tidak ditemukan');
    }
    if (item.active === false && !options?.allowInactive) {
        throw new Error('Barang gudang tidak aktif');
    }
    if (!item.itemCode || !item.name || !item.unit || !isInventoryUnit(item.unit)) {
        throw new Error('Master barang gudang tidak valid');
    }
    return item;
}

function assertTrackedTireQuantity(quantity: number, label: string) {
    if (!Number.isInteger(quantity) || quantity <= 0) {
        throw new Error(`${label} harus berupa bilangan bulat lebih besar dari 0 untuk barang gudang ban tertracking`);
    }
}

function assertTrackedTireWarehouseItemDefaults(item: WarehouseItem) {
    if (!isTireTrackedWarehouseItem(item)) {
        return;
    }
    if (!item.tireBrandDefault?.trim() || !item.tireSizeDefault?.trim()) {
        throw new Error(`Master ${item.itemCode || item.name || item._id} belum punya merk dan ukuran ban default`);
    }
    if (!normalizeOptionalTireType(item.tireTypeDefault)) {
        throw new Error(`Master ${item.itemCode || item.name || item._id} belum punya jenis ban default yang valid`);
    }
}

function normalizePurchaseLines(lines: unknown) {
    if (!Array.isArray(lines) || lines.length === 0) {
        throw new Error('Item pembelian wajib diisi');
    }

    const normalizedLines = lines.map((line, index) => {
        if (typeof line !== 'object' || line === null) {
            throw new Error(`Baris pembelian #${index + 1} tidak valid`);
        }
        const row = line as Record<string, unknown>;
        const warehouseItemRef = normalizeOptionalText(row.warehouseItemRef);
        const supplierItemPriceRef = normalizeOptionalText(row.supplierItemPriceRef);
        const orderedQty = parseInventoryQuantity(row.orderedQty);
        const unitPrice = parseWholeMoneyAmount(row.unitPrice);
        const priceOverrideReason = normalizeOptionalText(row.priceOverrideReason);
        const notes = normalizeOptionalText(row.notes);
        let newItem: PurchaseNewItemInput | undefined;
        if (row.newItem !== undefined && row.newItem !== null) {
            if (typeof row.newItem !== 'object' || Array.isArray(row.newItem)) {
                throw new Error(`Barang baru pada baris pembelian #${index + 1} tidak valid`);
            }
            const raw = row.newItem as Record<string, unknown>;
            const name = normalizeText(raw.name);
            if (!name) {
                throw new Error(`Nama barang baru pada baris pembelian #${index + 1} wajib diisi`);
            }
            const unit = normalizeText(raw.unit || 'PCS').toUpperCase();
            if (!isInventoryUnit(unit)) {
                throw new Error(`Satuan barang baru pada baris pembelian #${index + 1} tidak valid`);
            }
            newItem = {
                name,
                code: normalizeOptionalText(raw.code) || undefined,
                category: normalizeOptionalText(raw.category) || undefined,
                unit,
                trackingMode: raw.trackingMode === 'TIRE_ASSET' ? 'TIRE_ASSET' : 'STANDARD',
                tireTypeDefault: normalizeOptionalTireType(raw.tireTypeDefault) || undefined,
                tireBrandDefault: normalizeOptionalText(raw.tireBrandDefault) || undefined,
                tireSizeDefault: normalizeOptionalText(raw.tireSizeDefault) || undefined,
            };
        }
        if (!warehouseItemRef && !newItem) {
            throw new Error(`Barang pada baris pembelian #${index + 1} wajib dipilih`);
        }
        if (!Number.isFinite(orderedQty) || orderedQty <= 0) {
            throw new Error(`Qty pada baris pembelian #${index + 1} tidak valid`);
        }
        if (!Number.isFinite(unitPrice) || unitPrice <= 0) {
            throw new Error(`Harga pada baris pembelian #${index + 1} tidak valid`);
        }
        return {
            warehouseItemRef: warehouseItemRef || undefined,
            newItem,
            supplierItemPriceRef,
            orderedQty,
            unitPrice,
            priceOverrideReason,
            notes,
        } satisfies PurchaseCreateLine;
    });

    return normalizedLines;
}

function isSupplierPriceEffective(price: SupplierItemPriceDocument, orderDate: string) {
    const effectiveFrom = normalizeDateOnly(price.effectiveFrom);
    const effectiveTo = normalizeDateOnly(price.effectiveTo);
    if (price.active === false && !effectiveTo) return false;
    if (effectiveFrom && effectiveFrom > orderDate) return false;
    if (effectiveTo && effectiveTo < orderDate) return false;
    return true;
}

async function loadSupplierItemPricesForPurchase(params: {
    supplierRef: string;
    orderDate: string;
    lines: PurchaseCreateLine[];
}) {
    const explicitRefs = params.lines.map(line => line.supplierItemPriceRef).filter((value): value is string => Boolean(value));
    const itemRefs = params.lines.map(line => line.warehouseItemRef).filter((value): value is string => Boolean(value));
    const [explicitPrices, supplierPrices] = await Promise.all([
        explicitRefs.length > 0
            ? Promise.all(explicitRefs.map(ref => getDocumentById<SupplierItemPriceDocument>(ref, 'supplierItemPrice')))
            : Promise.resolve([]),
        listDocumentsByFilter<SupplierItemPriceDocument>('supplierItemPrice', {
            supplierRef: params.supplierRef,
            warehouseItemRef: itemRefs,
        }),
    ]);

    const byId = new Map<string, SupplierItemPriceDocument>();
    for (const price of explicitPrices) {
        if (price?._type === 'supplierItemPrice') {
            byId.set(price._id, price);
        }
    }

    const byItemRef = new Map<string, SupplierItemPriceDocument>();
    for (const price of supplierPrices) {
        if (!isSupplierPriceEffective(price, params.orderDate)) continue;
        const current = byItemRef.get(price.warehouseItemRef);
        const currentEffectiveFrom = normalizeDateOnly(current?.effectiveFrom);
        const nextEffectiveFrom = normalizeDateOnly(price.effectiveFrom);
        if (
            !current ||
            nextEffectiveFrom > currentEffectiveFrom ||
            (nextEffectiveFrom === currentEffectiveFrom && price.active !== false && current.active === false)
        ) {
            byItemRef.set(price.warehouseItemRef, price);
        }
    }

    return { byId, byItemRef };
}

function resolvePurchaseLinePriceSnapshot(params: {
    line: PurchaseCreateLine;
    item: WarehouseItemDocument;
    supplierPrice?: SupplierItemPriceDocument;
    orderDate: string;
}) {
    const supplierPriceAmount = params.supplierPrice
        ? Math.max(parseWholeMoneyAmount(params.supplierPrice.defaultPurchasePrice), 0)
        : 0;
    const warehouseDefaultPrice = Math.max(parseWholeMoneyAmount(params.item.defaultPurchasePrice ?? 0), 0);
    const sourcePrice = supplierPriceAmount > 0 ? supplierPriceAmount : warehouseDefaultPrice;
    const unitPrice = Math.max(parseWholeMoneyAmount(params.line.unitPrice), 0);
    const isManualOverride = sourcePrice > 0 && unitPrice !== sourcePrice;

    return {
        supplierItemPriceRef: params.supplierPrice?._id,
        priceSource: isManualOverride
            ? 'MANUAL'
            : params.supplierPrice
                ? 'SUPPLIER_PRICE'
                : 'WAREHOUSE_DEFAULT',
        priceEffectiveDate: normalizeDateOnly(params.supplierPrice?.effectiveFrom) || params.orderDate,
        originalUnitPrice: isManualOverride ? sourcePrice : undefined,
        priceOverridden: isManualOverride || undefined,
        priceOverrideReason: isManualOverride ? params.line.priceOverrideReason : undefined,
    } satisfies Pick<PurchaseItem, 'supplierItemPriceRef' | 'priceSource' | 'priceEffectiveDate' | 'originalUnitPrice' | 'priceOverridden' | 'priceOverrideReason'>;
}

export async function handlePurchaseCreate(
    session: ApiSession,
    data: Record<string, unknown>,
    addAuditLog: AuditLogFn
) {
    const createdItemIds: string[] = [];
    try {
        const supplierRef = normalizeOptionalText(data.supplierRef);
        const orderDate = normalizeOptionalText(data.orderDate) || getBusinessDateValue();
        const dueDate = normalizeOptionalText(data.dueDate);
        const notes = normalizeOptionalText(data.notes);
        const lines = normalizePurchaseLines(data.items);

        if (!supplierRef) {
            return NextResponse.json({ error: 'Supplier pembelian wajib dipilih' }, { status: 400 });
        }
        assertIsoDate(orderDate, 'Tanggal pembelian');
        if (dueDate) {
            assertIsoDate(dueDate, 'Jatuh tempo pembelian');
            if (dueDate < orderDate) {
                throw new Error('Jatuh tempo pembelian tidak boleh lebih awal dari tanggal pembelian');
            }
        }

        const supplier = await resolveSupplierSnapshot(supplierRef);
        const purchaseNumber = await getNextPurchaseNumber(orderDate);

        const hasNewItems = lines.some(line => line.newItem && !line.warehouseItemRef);
        if (hasNewItems && !hasPermission(session, 'warehouseItems', 'create')) {
            throw new Error('Anda tidak punya hak menambah barang gudang baru dari pembelian');
        }

        const itemSnapshots: WarehouseItemDocument[] = [];
        const resolvedRefs: string[] = [];
        const now = new Date().toISOString();
        for (const [index, line] of lines.entries()) {
            if (line.warehouseItemRef) {
                const item = await resolveWarehouseItemSnapshot(line.warehouseItemRef);
                itemSnapshots.push(item);
                resolvedRefs.push(item._id);
                continue;
            }
            if (!line.newItem) {
                throw new Error(`Barang pada baris pembelian #${index + 1} wajib dipilih`);
            }
            const existingByName = await findActiveWarehouseItemByName(line.newItem.name);
            if (existingByName) {
                const item = await resolveWarehouseItemSnapshot(existingByName._id);
                itemSnapshots.push(item);
                resolvedRefs.push(item._id);
                continue;
            }
            const itemCode = line.newItem.code || await getNextWarehouseItemCode(orderDate);
            const normalized = await normalizeWarehouseItemPayload({
                itemCode,
                name: line.newItem.name,
                category: line.newItem.category,
                unit: line.newItem.unit,
                trackingMode: line.newItem.trackingMode,
                minStockQty: 0,
                defaultSupplierRef: supplier._id,
                defaultPurchasePrice: line.unitPrice,
                tireTypeDefault: line.newItem.tireTypeDefault,
                tireBrandDefault: line.newItem.tireBrandDefault,
                tireSizeDefault: line.newItem.tireSizeDefault,
                active: true,
            });
            const itemId = `warehouse-item-${crypto.randomUUID()}`;
            const itemDoc: WarehouseItemDocument = {
                _id: itemId,
                _type: 'warehouseItem',
                ...normalized,
                createdBy: session._id,
                createdByName: session.name,
                createdAt: now,
                updatedAt: now,
            } as unknown as WarehouseItemDocument;
            await createDocument(itemDoc as unknown as { _type: string; [key: string]: unknown });
            createdItemIds.push(itemId);
            await addAuditLog(
                session,
                'CREATE',
                'warehouse-items',
                itemId,
                `Barang gudang ${String(normalized.itemCode || '')} - ${String(normalized.name || '')} dibuat dari pembelian ${purchaseNumber}`
            );
            itemSnapshots.push(itemDoc);
            resolvedRefs.push(itemId);
        }

        const uniqueRefs = new Set(resolvedRefs);
        if (uniqueRefs.size !== resolvedRefs.length) {
            throw new Error('Barang pembelian tidak boleh duplikat dalam satu dokumen');
        }

        const resolvedLines = lines.map((line, index) => ({ ...line, warehouseItemRef: resolvedRefs[index] }));
        const supplierPriceLookup = await loadSupplierItemPricesForPurchase({
            supplierRef: supplier._id,
            orderDate,
            lines: resolvedLines,
        });
        const lineSupplierPrices = lines.map((line, index) => {
            const resolvedRef = resolvedRefs[index];
            const price = line.supplierItemPriceRef
                ? supplierPriceLookup.byId.get(line.supplierItemPriceRef)
                : supplierPriceLookup.byItemRef.get(resolvedRef);
            if (line.supplierItemPriceRef && !price) {
                throw new Error(`Harga supplier pada baris pembelian #${index + 1} tidak ditemukan`);
            }
            if (!price) return undefined;
            if (price.supplierRef !== supplier._id || price.warehouseItemRef !== resolvedRef) {
                throw new Error(`Harga supplier pada baris pembelian #${index + 1} tidak sesuai supplier atau barang`);
            }
            if (!isSupplierPriceEffective(price, orderDate)) {
                throw new Error(`Harga supplier pada baris pembelian #${index + 1} tidak aktif untuk tanggal pembelian`);
            }
            return price;
        });
        itemSnapshots.forEach((item, index) => {
            if (isTireTrackedWarehouseItem(item)) {
                assertTrackedTireWarehouseItemDefaults(item);
                assertTrackedTireQuantity(lines[index].orderedQty, `Qty pesan untuk ${item.itemCode || item.name || `baris #${index + 1}`}`);
            }
        });
        const purchaseId = `purchase-${crypto.randomUUID()}`;

        const items = lines.map((line, index) => {
            const item = itemSnapshots[index];
            const priceSnapshot = resolvePurchaseLinePriceSnapshot({
                line,
                item,
                supplierPrice: lineSupplierPrices[index],
                orderDate,
            });
            return {
                _id: `purchase-item-${crypto.randomUUID()}`,
                _type: 'purchaseItem',
                purchaseRef: purchaseId,
                warehouseItemRef: item._id,
                supplierItemPriceRef: priceSnapshot.supplierItemPriceRef,
                itemCode: item.itemCode,
                itemName: item.name,
                itemUnit: item.unit,
                trackingMode: item.trackingMode,
                tireTypeDefault: normalizeOptionalTireType(item.tireTypeDefault) || undefined,
                tireBrandDefault: item.tireBrandDefault,
                tireSizeDefault: item.tireSizeDefault,
                orderedQty: line.orderedQty,
                receivedQty: 0,
                unitPrice: line.unitPrice,
                subtotal: Math.round(line.orderedQty * line.unitPrice),
                priceSource: priceSnapshot.priceSource,
                priceEffectiveDate: priceSnapshot.priceEffectiveDate,
                originalUnitPrice: priceSnapshot.originalUnitPrice,
                priceOverridden: priceSnapshot.priceOverridden,
                priceOverrideReason: priceSnapshot.priceOverrideReason,
                notes: line.notes,
            } satisfies PurchaseItem;
        });

        const summary = computePurchaseSummary({
            purchase: { status: 'ORDERED' },
            items,
            payments: [],
        });

        const purchaseDoc: Purchase = {
            _id: purchaseId,
            _type: 'purchase',
            purchaseNumber,
            supplierRef: supplier._id,
            supplierName: supplier.name,
            orderDate,
            dueDate: dueDate || undefined,
            status: 'ORDERED',
            notes,
            totalAmount: summary.totalAmount,
            totalOrderedQty: summary.totalOrderedQty,
            totalReceivedQty: 0,
            paidAmount: 0,
            outstandingAmount: summary.totalAmount,
            lineCount: items.length,
            createdBy: session._id,
            createdByName: session.name,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        };

        await createDocument(purchaseDoc as unknown as { _type: string; [key: string]: unknown });
        await Promise.all([
            updateDocument(supplier._id, { updatedAt: purchaseDoc.updatedAt }, 'supplier'),
            ...itemSnapshots.map(item => updateDocument(item._id, { updatedAt: purchaseDoc.updatedAt }, 'warehouseItem')),
            ...items.map(item => createDocument(item)),
        ]);

        await addAuditLog(
            session,
            'CREATE',
            'purchases',
            purchaseId,
            buildPurchaseAuditSummary(purchaseNumber, supplier.name, summary.totalAmount)
        );
        return NextResponse.json({ data: purchaseDoc, id: purchaseId });
    } catch (error) {
        if (createdItemIds.length > 0) {
            await Promise.allSettled(createdItemIds.map(id => deleteDocument(id, 'warehouseItem')));
        }
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Pembelian tidak valid' },
            { status: 400 }
        );
    }
}

export async function handlePurchaseReceive(
    session: ApiSession,
    data: Record<string, unknown>,
    addAuditLog: AuditLogFn
) {
    try {
        const purchaseRef = normalizeOptionalText(data.purchaseRef) || normalizeOptionalText(data.id);
        const receiveDate = normalizeOptionalText(data.receiveDate) || getBusinessDateValue();
        const receiptItems = Array.isArray(data.items) ? data.items : [];
        if (!purchaseRef) {
            return NextResponse.json({ error: 'Pembelian wajib dipilih' }, { status: 400 });
        }
        assertIsoDate(receiveDate, 'Tanggal terima barang');

        const bundle = await loadPurchaseBundle(purchaseRef);
        if (!bundle) {
            return NextResponse.json({ error: 'Pembelian tidak ditemukan' }, { status: 404 });
        }
        if (receiveDate < bundle.purchase.orderDate) {
            return NextResponse.json(
                { error: 'Tanggal terima barang tidak boleh lebih awal dari tanggal pembelian' },
                { status: 400 }
            );
        }
        const lastReceivedDate = normalizeDateOnly(bundle.purchase.lastReceivedAt);
        if (lastReceivedDate && receiveDate < lastReceivedDate) {
            return NextResponse.json(
                { error: 'Tanggal terima barang tidak boleh lebih awal dari penerimaan terakhir pembelian ini' },
                { status: 400 }
            );
        }
        if (bundle.purchase.status === 'CANCELLED') {
            return NextResponse.json({ error: 'Pembelian yang dibatalkan tidak bisa menerima barang' }, { status: 409 });
        }

        const validPurchaseItemIds = new Set(bundle.items.map(item => item._id));
        const receiptMap = new Map<string, { receivedQty: number; note?: string }>();
        for (const [index, rawItem] of receiptItems.entries()) {
            if (typeof rawItem !== 'object' || rawItem === null) {
                return NextResponse.json({ error: `Baris penerimaan #${index + 1} tidak valid` }, { status: 400 });
            }
            const row = rawItem as Record<string, unknown>;
            const purchaseItemRef = normalizeOptionalText(row.purchaseItemRef);
            const receivedQty = parseInventoryQuantity(row.receivedQty);
            const note = normalizeOptionalText(row.note);
            if (!purchaseItemRef) {
                return NextResponse.json({ error: `Item pembelian pada baris penerimaan #${index + 1} tidak valid` }, { status: 400 });
            }
            if (!validPurchaseItemIds.has(purchaseItemRef)) {
                return NextResponse.json(
                    { error: `Item pada baris penerimaan #${index + 1} bukan milik dokumen pembelian ini` },
                    { status: 409 }
                );
            }
            if (!Number.isFinite(receivedQty) || receivedQty < 0) {
                return NextResponse.json({ error: `Qty terima pada baris #${index + 1} tidak valid` }, { status: 400 });
            }
            if (receivedQty > 0) {
                if (receiptMap.has(purchaseItemRef)) {
                    return NextResponse.json(
                        { error: `Item pada baris penerimaan #${index + 1} duplikat dalam satu dokumen terima barang` },
                        { status: 400 }
                    );
                }
                receiptMap.set(purchaseItemRef, { receivedQty, note });
            }
        }

        if (receiptMap.size === 0) {
            return NextResponse.json({ error: 'Isi minimal satu qty terima lebih besar dari 0' }, { status: 400 });
        }

        const nextItems: PurchaseItem[] = [];
        const movementDocs: StockMovement[] = [];
        const registeredTires: TireEvent[] = [];
        const receiptTargetItems = bundle.items.filter((item) => receiptMap.has(item._id));
        const latestStockMovementDates = await getLatestWarehouseStockMovementDateMap(
            receiptTargetItems.map((item) => item.warehouseItemRef)
        );

        for (const [itemIndex, item] of bundle.items.entries()) {
            const receipt = receiptMap.get(item._id);
            if (!receipt) {
                nextItems.push(item);
                continue;
            }
            const remainingQty = Math.max(parseInventoryQuantity(item.orderedQty) - parseInventoryQuantity(item.receivedQty ?? 0), 0);
            if (receipt.receivedQty > remainingQty) {
                return NextResponse.json(
                    { error: `Qty terima untuk ${item.itemName || item.itemCode || item._id} melebihi sisa pesanan` },
                    { status: 409 }
                );
            }
            const warehouseItem = await resolveWarehouseItemSnapshot(item.warehouseItemRef, { allowInactive: true });
            const latestStockMovementDate = latestStockMovementDates.get(warehouseItem._id);
            if (latestStockMovementDate && receiveDate < latestStockMovementDate) {
                return NextResponse.json(
                    {
                        error: `Tanggal terima barang untuk ${warehouseItem.itemCode || warehouseItem.name || warehouseItem._id} tidak boleh lebih awal dari mutasi stok terakhir barang ini`,
                    },
                    { status: 400 }
                );
            }
            if (isTireTrackedWarehouseItem(item) || isTireTrackedWarehouseItem(warehouseItem)) {
                assertTrackedTireWarehouseItemDefaults(warehouseItem);
                assertTrackedTireQuantity(
                    receipt.receivedQty,
                    `Qty terima untuk ${item.itemName || item.itemCode || item._id}`
                );
            }
            const currentStockQty = Math.max(parseInventoryQuantity(warehouseItem.currentStockQty ?? 0), 0);
            const nextStockQty = currentStockQty + receipt.receivedQty;
            const nextReceivedQty = Math.max(parseInventoryQuantity(item.receivedQty ?? 0), 0) + receipt.receivedQty;
            const unitCostSnapshot = Math.max(parseWholeMoneyAmount(item.unitPrice), 0);
            const subtotalCost = Math.round(receipt.receivedQty * unitCostSnapshot);

            await updateDocument(item._id, { receivedQty: nextReceivedQty }, 'purchaseItem');
            await updateDocument(warehouseItem._id, { currentStockQty: nextStockQty }, 'warehouseItem');

            const movementDoc = buildTrackedTireStockMovementDoc({
                warehouseItem,
                quantity: receipt.receivedQty,
                balanceAfter: nextStockQty,
                movementDate: receiveDate,
                type: 'IN',
                sourceType: 'PURCHASE_RECEIPT',
                sourceRef: bundle.purchase._id,
                sourceNumber: bundle.purchase.purchaseNumber,
                unitCostSnapshot,
                subtotalCost,
                costMethod: 'PURCHASE_PRICE',
                note: receipt.note,
                createdBy: session._id,
                createdByName: session.name,
            });
            await createDocument(movementDoc as unknown as { _type: string; [key: string]: unknown });
            movementDocs.push(movementDoc);

            if (isTireTrackedWarehouseItem(item) || isTireTrackedWarehouseItem(warehouseItem)) {
                const batchStart = Math.max(parseInventoryQuantity(item.receivedQty ?? 0), 0);
                for (let sequence = 1; sequence <= receipt.receivedQty; sequence += 1) {
                    const nextSequence = batchStart + sequence;
                    const tireCode = buildAutoGeneratedTireCode({
                        purchaseNumber: bundle.purchase.purchaseNumber,
                        lineSequence: itemIndex + 1,
                        tireSequence: nextSequence,
                    });
                    const tireDoc: TireEvent = {
                        _id: `tire-event-${crypto.randomUUID()}`,
                        _type: 'tireEvent',
                        tireCode,
                        holderType: 'WAREHOUSE',
                        status: 'IN_WAREHOUSE',
                        posisi: 'Gudang Ban',
                        tireType: normalizeTireType(warehouseItem.tireTypeDefault || item.tireTypeDefault),
                        tireBrand: warehouseItem.tireBrandDefault || item.tireBrandDefault || item.itemName || warehouseItem.name,
                        tireSize: warehouseItem.tireSizeDefault || item.tireSizeDefault || '-',
                        linkedWarehouseItemRef: warehouseItem._id,
                        linkedWarehouseItemCode: warehouseItem.itemCode,
                        linkedWarehouseItemName: warehouseItem.name,
                        sourcePurchaseRef: bundle.purchase._id,
                        sourcePurchaseNumber: bundle.purchase.purchaseNumber,
                        sourcePurchaseItemRef: item._id,
                        sourceReceiveDate: receiveDate,
                        installDate: receiveDate,
                        purchaseCost: Number(item.unitPrice || 0),
                        originalCost: Number(item.unitPrice || 0),
                        totalUsedPercent: 0,
                        remainingPercent: 100,
                        remainingValue: Number(item.unitPrice || 0),
                        notes: `Terdaftar otomatis dari pembelian ${bundle.purchase.purchaseNumber}`,
                    };
                    const historyLogDoc = buildTireHistoryLogDoc({
                        tireEventRef: tireDoc._id,
                        tireCode: tireDoc.tireCode,
                        tireBrand: tireDoc.tireBrand,
                        tireSize: tireDoc.tireSize,
                        previous: null,
                        next: buildTireHistorySnapshot(tireDoc),
                        session,
                        note: `Ban diterima dari pembelian ${bundle.purchase.purchaseNumber} dan masuk ke gudang ban`,
                    });
                    await createDocument(tireDoc as unknown as { _type: string; [key: string]: unknown });
                    await createDocument(historyLogDoc);
                    registeredTires.push(tireDoc);
                }
            }
            nextItems.push({ ...item, receivedQty: nextReceivedQty });
        }

        const summary = computePurchaseSummary({
            purchase: bundle.purchase,
            items: nextItems,
            payments: bundle.payments,
        });
        const nextStatus = computePurchaseStatus({
            totalOrderedQty: summary.totalOrderedQty,
            totalReceivedQty: summary.totalReceivedQty,
            totalAmount: summary.totalAmount,
            paidAmount: summary.paidAmount,
            existingStatus: bundle.purchase.status,
        });
        await updateDocument(bundle.purchase._id, {
            totalReceivedQty: summary.totalReceivedQty,
            status: nextStatus,
            lastReceivedAt: receiveDate,
            updatedAt: new Date().toISOString(),
        }, 'purchase');
        const receivedValue = bundle.items.reduce((sum, item) => {
            const receipt = receiptMap.get(item._id);
            return sum + (receipt ? receipt.receivedQty * parseWholeMoneyAmount(item.unitPrice) : 0);
        }, 0);
        const receiptBatchRef = movementDocs.map(item => item._id).join('|') || `${bundle.purchase._id}:${receiveDate}`;
        await postPurchaseReceiptJournal(session, bundle.purchase, receiveDate, receivedValue, receiptBatchRef);

        await addAuditLog(
            session,
            'UPDATE',
            'purchases',
            bundle.purchase._id,
            `Terima barang untuk ${bundle.purchase.purchaseNumber} sebesar ${summary.totalReceivedQty}/${summary.totalOrderedQty}`
        );
        return NextResponse.json({
            success: true,
            data: {
                purchaseRef: bundle.purchase._id,
                stockMovements: movementDocs,
                registeredTires,
            },
        });
    } catch (error) {
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Penerimaan barang tidak valid' },
            { status: 400 }
        );
    }
}

export async function handleStockMovementCreate(
    session: ApiSession,
    data: Record<string, unknown>,
    addAuditLog: AuditLogFn
) {
    try {
        const warehouseItemRef = normalizeOptionalText(data.warehouseItemRef);
        const movementDate = normalizeOptionalText(data.movementDate) || getBusinessDateValue();
        const sourceType = normalizeText(data.sourceType).toUpperCase() as StockMovementSourceType;
        const quantity = parseInventoryQuantity(data.quantity);
        const note = normalizeOptionalText(data.note);

        if (!warehouseItemRef) {
            return NextResponse.json({ error: 'Barang gudang wajib dipilih' }, { status: 400 });
        }
        if (sourceType !== 'MANUAL_IN' && sourceType !== 'MANUAL_OUT') {
            return NextResponse.json({ error: 'Tipe mutasi stok manual tidak valid' }, { status: 400 });
        }
        assertIsoDate(movementDate, 'Tanggal mutasi stok');
        if (!Number.isFinite(quantity) || quantity <= 0) {
            return NextResponse.json({ error: 'Qty mutasi stok tidak valid' }, { status: 400 });
        }

        const warehouseItem = await resolveWarehouseItemSnapshot(warehouseItemRef);
        const latestStockMovementDates = await getLatestWarehouseStockMovementDateMap([warehouseItem._id]);
        const latestStockMovementDate = latestStockMovementDates.get(warehouseItem._id);
        if (latestStockMovementDate && movementDate < latestStockMovementDate) {
            return NextResponse.json(
                { error: 'Tanggal mutasi stok tidak boleh lebih awal dari mutasi stok terakhir barang ini' },
                { status: 400 }
            );
        }
        if (isTireTrackedWarehouseItem(warehouseItem)) {
            return NextResponse.json(
                { error: 'Mutasi stok manual untuk ban tertracking dikelola lewat modul Ban dan penerimaan pembelian' },
                { status: 409 }
            );
        }
        const currentStockQty = Math.max(parseInventoryQuantity(warehouseItem.currentStockQty ?? 0), 0);
        if (sourceType === 'MANUAL_OUT' && currentStockQty < quantity) {
            return NextResponse.json({ error: 'Stok barang tidak cukup untuk dikeluarkan' }, { status: 409 });
        }
        const nextStockQty = sourceType === 'MANUAL_OUT' ? currentStockQty - quantity : currentStockQty + quantity;
        const unitCostSnapshot = Math.max(parseWholeMoneyAmount(warehouseItem.defaultPurchasePrice ?? 0), 0);
        const subtotalCost = Math.round(quantity * unitCostSnapshot);
        const movementDoc: StockMovement = {
            _id: `stock-movement-${crypto.randomUUID()}`,
            _type: 'stockMovement',
            warehouseItemRef: warehouseItem._id,
            itemCode: warehouseItem.itemCode,
            itemName: warehouseItem.name,
            unit: warehouseItem.unit,
            movementDate,
            type: sourceType === 'MANUAL_OUT' ? 'OUT' : 'IN',
            sourceType,
            quantity,
            balanceAfter: nextStockQty,
            unitCostSnapshot,
            subtotalCost,
            costMethod: 'WAREHOUSE_DEFAULT',
            note,
            createdBy: session._id,
            createdByName: session.name,
        };

        await updateDocument(warehouseItem._id, { currentStockQty: nextStockQty }, 'warehouseItem');
        await createDocument(movementDoc as unknown as { _type: string; [key: string]: unknown });
        await postStockMovementJournal(
            session,
            movementDoc,
            unitCostSnapshot
        );

        await addAuditLog(
            session,
            'CREATE',
            'stock-movements',
            movementDoc._id,
            buildStockMovementAuditSummary({
                itemName: warehouseItem.name,
                itemCode: warehouseItem.itemCode,
                quantity,
                sourceType,
                note,
            })
        );
        return NextResponse.json({ data: movementDoc, id: movementDoc._id });
    } catch (error) {
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Mutasi stok tidak valid' },
            { status: 400 }
        );
    }
}

export async function handlePurchasePaymentCreate(
    session: ApiSession,
    data: Record<string, unknown>,
    addAuditLog: AuditLogFn
) {
    try {
        const purchaseRef = normalizeOptionalText(data.purchaseRef);
        const bankAccountRef = normalizeOptionalText(data.bankAccountRef);
        const date = normalizeOptionalText(data.date) || getBusinessDateValue();
        const amount = parseWholeMoneyAmount(data.amount);
        const note = normalizeOptionalText(data.note);

        if (!purchaseRef) {
            return NextResponse.json({ error: 'Pembelian wajib dipilih' }, { status: 400 });
        }
        if (!bankAccountRef) {
            return NextResponse.json({ error: 'Rekening pembayaran supplier wajib dipilih' }, { status: 400 });
        }
        assertIsoDate(date, 'Tanggal pembayaran supplier');
        if (!Number.isFinite(amount) || amount <= 0) {
            return NextResponse.json({ error: 'Nominal pembayaran supplier tidak valid' }, { status: 400 });
        }

        const bundle = await loadPurchaseBundle(purchaseRef);
        if (!bundle) {
            return NextResponse.json({ error: 'Pembelian tidak ditemukan' }, { status: 404 });
        }
        if (date < bundle.purchase.orderDate) {
            return NextResponse.json(
                { error: 'Tanggal pembayaran supplier tidak boleh lebih awal dari tanggal pembelian' },
                { status: 400 }
            );
        }
        const lastPaymentDate = normalizeDateOnly(bundle.purchase.lastPaidAt);
        if (lastPaymentDate && date < lastPaymentDate) {
            return NextResponse.json(
                { error: 'Tanggal pembayaran supplier tidak boleh lebih awal dari pembayaran terakhir pembelian ini' },
                { status: 400 }
            );
        }
        if (bundle.purchase.status === 'CANCELLED') {
            return NextResponse.json({ error: 'Pembelian yang dibatalkan tidak bisa dibayar' }, { status: 409 });
        }

        const summary = computePurchaseSummary({
            purchase: bundle.purchase,
            items: bundle.items,
            payments: bundle.payments,
        });
        if (summary.outstandingAmount <= 0) {
            return NextResponse.json({ error: 'Pembelian ini sudah lunas' }, { status: 409 });
        }
        if (amount > summary.outstandingAmount) {
            return NextResponse.json({ error: 'Nominal bayar melebihi outstanding pembelian' }, { status: 409 });
        }

        const bankAccount = await getLedgerAccount(bankAccountRef);
        if (!bankAccount) {
            return NextResponse.json({ error: 'Rekening pembayaran supplier tidak ditemukan' }, { status: 404 });
        }
        const ledger = computeLedgerDebitBalance(bankAccount.currentBalance, amount);
        if (ledger.nextBalance < 0) {
            return NextResponse.json({ error: 'Saldo rekening tidak cukup untuk membayar supplier' }, { status: 409 });
        }

        const paymentId = `purchase-payment-${crypto.randomUUID()}`;
        const transactionId = `bank-transaction-${crypto.randomUUID()}`;
        const paymentDoc: PurchasePayment = {
            _id: paymentId,
            _type: 'purchasePayment',
            purchaseRef: bundle.purchase._id,
            purchaseNumber: bundle.purchase.purchaseNumber,
            supplierRef: bundle.purchase.supplierRef,
            supplierName: bundle.purchase.supplierName,
            date,
            amount,
            bankAccountRef: bankAccount._id,
            bankAccountName: bankAccount.bankName,
            bankAccountNumber: bankAccount.accountNumber,
            bankTransactionRef: transactionId,
            note,
            createdBy: session._id,
            createdByName: session.name,
        };
        const nextPayments = [...bundle.payments, paymentDoc];
        const nextSummary = computePurchaseSummary({
            purchase: bundle.purchase,
            items: bundle.items,
            payments: nextPayments,
        });
        const nextStatus = computePurchaseStatus({
            totalOrderedQty: nextSummary.totalOrderedQty,
            totalReceivedQty: nextSummary.totalReceivedQty,
            totalAmount: nextSummary.totalAmount,
            paidAmount: nextSummary.paidAmount,
            existingStatus: bundle.purchase.status,
        });

        await createDocument(paymentDoc as unknown as { _type: string; [key: string]: unknown });
        await createDocument({
            _id: transactionId,
            _type: 'bankTransaction',
            bankAccountRef: bankAccount._id,
            bankAccountName: bankAccount.bankName,
            bankAccountNumber: bankAccount.accountNumber,
            type: 'DEBIT',
            amount,
            date,
            description: `Pembayaran supplier ${bundle.purchase.purchaseNumber} - ${bundle.purchase.supplierName || '-'}`,
            balanceAfter: ledger.nextBalance,
            relatedPurchasePaymentRef: paymentId,
            relatedPurchaseRef: bundle.purchase._id,
        });
        // Bank balance update via recompute to ensure consistency
        await recomputeBankLedgerBalancesForAccounts([bankAccount._id]);
        await updateDocument(bundle.purchase._id, {
            paidAmount: nextSummary.paidAmount,
            outstandingAmount: nextSummary.outstandingAmount,
            status: nextStatus,
            lastPaidAt: date,
            updatedAt: new Date().toISOString(),
        }, 'purchase');
        await postPurchasePaymentJournal(session, paymentDoc, bankAccount);

        await addAuditLog(
            session,
            'CREATE',
            'purchase-payments',
            paymentId,
            buildPurchasePaymentAuditSummary({
                purchaseNumber: bundle.purchase.purchaseNumber,
                supplierName: bundle.purchase.supplierName || '-',
                amount,
                bankName: bankAccount.bankName,
                note,
            })
        );
        return NextResponse.json({ data: paymentDoc, id: paymentId });
    } catch (error) {
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Pembayaran supplier tidak valid' },
            { status: 400 }
        );
    }
}
